### ISSUE TITLE
Many buttons are disabled on my Mac

### ISSUE THREAD

**Issue by Carmen14edo** [vsicurella/SuperVirtualKeyboard#16]
These buttons are all grayed out/disabled:
Edit Colors,
Nested Center, Adjacent,
Inside, Border, Circles, Squares,
Manuel Map

Also when I hit Clicked Auto Mapping my DAW outright crashed

**Comment by vsicurella** [comment]
Thanks for submitting the issues! The older alpha versions are the only available releases right now, and the inner workings have changed a lot since then. I am trying to get out an updated release soon!

However, I still haven't implemented some of the secondary features I suppose I was a little too eager about - the Highlighting styles (Inside, border, etc.) and Manual Mapping haven't been done yet, but will probably be some of my main focuses following the next release.

Could you let me know what DAW you use?

**Comment by Carmen14edo** [comment]
Yeah I use Reaper. Thank you very much for working on designing this
indispensable VST

**Comment by vsicurella** [comment]
Thanks Carmen, that really means a lot to me :)

I am almost done with a new version! It includes all the options that were disabled before.

I think it's safe to try a preview version - you can email me at someone@everytone.zone if you'd like to try it out!
