### ISSUE TITLE
No binaries and instructions provided.

### ISSUE THREAD

**Issue by evguu** [vsicurella/SuperVirtualKeyboard#19]
Please provide compiled binaries of the completed product or instructions how to make them.

**Comment by vsicurella** [comment]
Hey, thanks for your interest in this project!
There are some binaries here: https://github.com/vsicurella/SuperVirtualKeyboard/releases/tag/0.021

This is still an "early alpha" version so if you use it in a DAW, I would be cautious about saving/relying on it in any projects, and would suggest using it to help record MIDI and de-instantiating before saving your project.

I'm not 100% the branch with my most recent activity is buildable or functional at the moment because I left off rewriting a bunch of internal stuff. But if you are interested anyway, it's a simple [JUCE project](https://juce.com/) so the build process consists of opening the project file in Projucer, which comes with JUCE, launching XCode or VisualStudio and using the build action, or using the Makefile for Linux. Bear in mind I think I left off with JUCE 5 so things may not be as straightforward in JUCE 6 or 7.

I don't intend on abandoning this project, and when I reach a point where I am more comfortable with it's stability and reliability then I will make it much more accessible to run and also create some more guides and videos on how to use certain features.
